version: '1.0.{build}'

image: Visual Studio 2017
clone_depth: 5

# Maximum number of concurrent jobs for the project
max_jobs: 1

platform:
  - x64

# Build configuration
configuration:
  - RelWithDebInfo
  # - Debug

environment:
  matrix:
    - MSVC_ARCH: x64
      BOOST_ROOT: C:\Libraries\boost_1_65_1
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_65_1\boost
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_65_1\lib64-msvc-14.1
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    - MSVC_ARCH: x86
      BOOST_ROOT: C:\Libraries\boost_1_65_1
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_65_1\boost
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_65_1\lib32-msvc-14.1
      CMAKE_GENERATOR: "Visual Studio 15 2017"

# Branches to build
branches:
  only:
    - master

skip_commits:
  message: /cmake|appveyor/\[contrib\]/

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - git submodule update --init --recursive
  - set PATH=%BOOST_LIBRARYDIR%;%PATH%
  - if defined MSVC_ARCH call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %MSVC_ARCH%

before_build:
  - if not exist Build mkdir Build
  - cd Build
  - cmake -G "%CMAKE_GENERATOR%" -DCry_CIL_BUILD_EXAMPLE=ON -DCry_MOD_BUILD_EXAMPLE=ON -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -V --build-config %CONFIGURATION%

# Disable artefacts as there is a storage limit
artifacts:
 - path: '**\bin\$(configuration)\*.dll'
   name: Deliverables
 
 - path: '**\bin\$(configuration)\*.exe'
   name: Deliverables
 
#  - path: '**\bin\$(configuration)\*.pdb'
#    name: Diagnostics
