version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

cache:
  - c:/Users/appveyor/.cppan/storage

configuration:
  - Release

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
