version: '1.0.{build}'

image: Visual Studio 2017
clone_depth: 1

platform:
  - x64

cache:
  - c:/Users/appveyor/.cppan/storage

# Build configuration
configuration:
  - Release

# Branches to build
branches:
  only:
    - master

before_build:
  - git submodule update --init
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
