version: '1.0.{build}'

image: Visual Studio 2017
clone_depth: 5

# Maximum number of concurrent jobs for the project
max_jobs: 1

platform:
  - x64

# Build configuration
configuration:
  - Release

environment:
  matrix:
    - MSVC_ARCH: x64
      BOOST_ROOT: C:\Libraries\boost_1_65_1
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_65_1\boost
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_65_1\lib64-msvc-14.1
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

# Branches to build
branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - set PATH=%BOOST_LIBRARYDIR%;%PATH%
  - if defined MSVC_ARCH call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %MSVC_ARCH%

build_script:
  - dir
  - md build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
  - cmake --build . --config %configuration%
